In [14]:
from SE3 import se3, SE3
from SO3 import so3, DCM, Euler, MRP, Quat
from SE2 import se2, SE2
from SO2 import so2, SO2
import numpy as np
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
x = np.array([1,2,3,0.1,0.2,0.3])
y = np.array([2,4,6,0.01,0.02,0.03])
theta = x[3:6]

In [16]:
#test so3
a = so3(theta)
aw = a.wedge
print('wedge:', aw)
av = so3.vee(aw)
print('vee:', av)

A = DCM.exp(a)
print('exp:', A)
theta_group = Euler.from_dcm(A)
print('exp_ele:', theta_group)

wedge: [[ 0.  -0.3  0.2]
 [ 0.3  0.  -0.1]
 [-0.2  0.1  0. ]]
vee: [0.1 0.2 0.3]
exp: [[ 0.9357548  -0.28316496  0.21019171]
 [ 0.30293271  0.95058062 -0.06803132]
 [-0.18054008  0.12733457  0.97529031]]
exp_ele: [0.12982634 0.18153552 0.31308358]


In [19]:
# test SO3
B = DCM.from_euler(theta_group) 
print('SO3:', B)
print('inv', DCM(B).inv)
b = DCM.log(DCM(B))
print('log:', b)
print('log_v:', so3.vee(b))


SO3: [[ 0.9357548  -0.28316496  0.21019171]
 [ 0.30293271  0.95058062 -0.06803132]
 [-0.18054008  0.12733457  0.97529031]]
inv [[ 0.9357548   0.30293271 -0.18054008]
 [-0.28316496  0.95058062  0.12733457]
 [ 0.21019171 -0.06803132  0.97529031]]
log: [[ 0.  -0.3  0.2]
 [ 0.3  0.  -0.1]
 [-0.2  0.1  0. ]]
log_v: [0.1 0.2 0.3]


In [20]:
# check inv
DCM(B).inv@B

array([[ 1.00000000e+00, -6.20201117e-17,  4.00608379e-18],
       [-6.20201117e-17,  1.00000000e+00,  1.71882035e-19],
       [ 4.00608379e-18,  1.71882035e-19,  1.00000000e+00]])

In [21]:
# test se3
c = se3(x)
print(c.w)
cw = c.wedge
print('wedge:', cw)
print('vee:', se3.vee(cw))

C = SE3.exp(c)
print('exp:', C)
C_group = SE3.to_vec(C)
print('exp_ele:', C_group)

[[ 0.  -0.3  0.2]
 [ 0.3  0.  -0.1]
 [-0.2  0.1  0. ]]
wedge: [[ 0.  -0.3  0.2  1. ]
 [ 0.3  0.  -0.1  2. ]
 [-0.2  0.1  0.   3. ]
 [ 0.   0.   0.   0. ]]
vee: [1.  2.  3.  0.1 0.2 0.3]
exp: [[ 0.9357548  -0.28316496  0.21019171  1.        ]
 [ 0.30293271  0.95058062 -0.06803132  2.        ]
 [-0.18054008  0.12733457  0.97529031  3.        ]
 [ 0.          0.          0.          1.        ]]
exp_ele: [1.         2.         3.         0.12982634 0.18153552 0.31308358]


In [22]:
c.ad_matrix

array([[ 0. , -0.3,  0.2,  0. , -3. ,  2. ],
       [ 0.3,  0. , -0.1,  3. ,  0. , -1. ],
       [-0.2,  0.1,  0. , -2. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. , -0.3,  0.2],
       [ 0. ,  0. ,  0. ,  0.3,  0. , -0.1],
       [ 0. ,  0. ,  0. , -0.2,  0.1,  0. ]])

Note that the elements of SE3 Lie group has to use [x,y,z,theta1,theta2,theta3] (pos, euler angles)

if you have your angle in other format, use SO3 class to do the transformation first

In [24]:
# test SE3
D = SE3(C_group)
print('SE3:', D.to_matrix)
print('inv:', D.inv)
d = SE3.log(D) 
print('log:', d)
print('log_vee:', se3.vee(d))

SE3: [[ 0.9357548  -0.28316496  0.21019171  1.        ]
 [ 0.30293271  0.95058062 -0.06803132  2.        ]
 [-0.18054008  0.12733457  0.97529031  3.        ]
 [ 0.          0.          0.          1.        ]]
inv: [[ 0.9357548   0.30293271 -0.18054008 -1.        ]
 [-0.28316496  0.95058062  0.12733457 -2.        ]
 [ 0.21019171 -0.06803132  0.97529031 -3.        ]
 [ 0.          0.          0.          1.        ]]


NameError: name 'p' is not defined

In [ ]:
# check inv
D.to_matrix@D.inv