In [1]:
import SE3Lie
import SO3Lie
import numpy as np

In [2]:
SE3 = SE3Lie.SE3
se3 = SE3Lie.se3
DCM = SO3Lie.SO3DCM
Euler = SO3Lie.SO3Euler
so3 = SO3Lie.so3

In [3]:
x = np.array([1,2,3,0.1,0.2,0.3])
theta = x[3:6]

In [4]:
#test so3
a = so3(theta)
aw = a.wedge
print('wedge:', aw)
av = so3.vee(aw)
print('vee:', av)

A = so3.exp(aw)
print('exp:', A)
theta_group = Euler.from_dcm(A)
print('exp_ele:', theta_group)

wedge: [[ 0.  -0.3  0.2]
 [ 0.3  0.  -0.1]
 [-0.2  0.1  0. ]]
vee: [0.1 0.2 0.3]
exp: [[ 0.9357548  -0.28316496  0.21019171]
 [ 0.30293271  0.95058062 -0.06803132]
 [-0.18054008  0.12733457  0.97529031]]
exp_ele: [0.12982634 0.18153552 0.31308358]


In [5]:
# test SO3
B = DCM.from_euler(theta_group) 
print('SO3:', B)
print('inv', DCM(B).inv)
b = DCM(B).log
print('log:', b)
print('log_v:', so3.vee(b))


SO3: [[ 0.9357548  -0.28316496  0.21019171]
 [ 0.30293271  0.95058062 -0.06803132]
 [-0.18054008  0.12733457  0.97529031]]
inv [[ 0.9357548   0.30293271 -0.18054008]
 [-0.28316496  0.95058062  0.12733457]
 [ 0.21019171 -0.06803132  0.97529031]]
log: [[ 0.  -0.3  0.2]
 [ 0.3  0.  -0.1]
 [-0.2  0.1  0. ]]
log_v: [0.1 0.2 0.3]


In [6]:
# check inv
DCM(B).inv@B

array([[ 1.00000000e+00, -6.20201117e-17,  4.00608379e-18],
       [-6.20201117e-17,  1.00000000e+00,  1.71882035e-19],
       [ 4.00608379e-18,  1.71882035e-19,  1.00000000e+00]])

In [7]:
# test se3
c = se3(x)
cw = c.wedge
print('wedge:', cw)
print('vee:', se3.vee(cw))

C = se3.exp(cw)
print('exp:', C)
C_group = SE3.to_vec(C)
print('exp_ele:', C_group)

wedge: [[ 0.  -0.3  0.2  1. ]
 [ 0.3  0.  -0.1  2. ]
 [-0.2  0.1  0.   3. ]
 [ 0.   0.   0.   0. ]]
vee: [1.  2.  3.  0.1 0.2 0.3]
exp: [[ 0.9357548  -0.28316496  0.21019171  1.        ]
 [ 0.30293271  0.95058062 -0.06803132  2.        ]
 [-0.18054008  0.12733457  0.97529031  3.        ]
 [ 0.          0.          0.          1.        ]]
exp_ele: [1.         2.         3.         0.12982634 0.18153552 0.31308358]


In [8]:
# test SE3
D = SE3(C_group)
print('SE3:', D.M)
print('inv:', D.inv)
d = SE3.log(D.M) 
print('log:', d)
print('log_vee:', se3.vee(d))

SE3: [[ 0.9357548  -0.28316496  0.21019171  1.        ]
 [ 0.30293271  0.95058062 -0.06803132  2.        ]
 [-0.18054008  0.12733457  0.97529031  3.        ]
 [ 0.          0.          0.          1.        ]]
inv: [[ 0.9357548   0.30293271 -0.18054008 -1.        ]
 [-0.28316496  0.95058062  0.12733457 -2.        ]
 [ 0.21019171 -0.06803132  0.97529031 -3.        ]
 [ 0.          0.          0.          1.        ]]
log: [[ 0.  -0.3  0.2  1. ]
 [ 0.3  0.  -0.1  2. ]
 [-0.2  0.1  0.   3. ]
 [ 0.   0.   0.   0. ]]
log_vee: [1.  2.  3.  0.1 0.2 0.3]


In [9]:
# check inv
D.M@D.inv

array([[ 1.00000000e+00, -5.73362522e-17, -4.00266198e-17,
         0.00000000e+00],
       [-5.73362522e-17,  1.00000000e+00,  1.10537728e-17,
        -6.66133815e-16],
       [-4.00266198e-17,  1.10537728e-17,  1.00000000e+00,
        -4.44089210e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])