In [1]:
from SE3 import se3, SE3
from SO3 import so3, DCM, Euler, MRP, Quat
from SE2 import se2, SE2
from SO2 import so2, SO2
import numpy as np
%load_ext autoreload
%autoreload 2

All inputs for group/algebra has to be np.array([]) (e.g., se3(x) where x is a np.array which has shape (6,1) or (6,))

Algebra:

- property: wedge, ad_matrix
- method: vee (input: Lie algebra matrix, output: vector of algebra element)

Group:

- property: to_matrix, inv, Ad_matrix
- method: 
    - to_vect (input: Lie group matrix, output: vector of Group element)
    - log (input: Group (e.g., SE3(x)), output: return Algebra) 
    - exp (input: Algebra (e.g., se3(x)), output: return Group)

** use wedge/to_matrix get the algebra/group to a matrix of np.array (e.g., SE3(x).to_matrix, se3(x).wedge)

** use .param get the element of group/algebra to a vector of np.array (e.g., x = se3(x).param)

** inputs for tranformation in SO3 should be np.array (e.g., DCM.from_euler(np.array), Euler.from_dcm(np.array))

** both @ and * can do multiplication for group, both matrix has to be in same group! return group

** @ still can do np array/matrix multiplication, as long as two elements are both in np, return np array

In [2]:
x1 = np.array([0,0,0,0,0,0])
x2 = np.array([1,1,2,0,0,0])

In [3]:
X1 = SE3(x1)
X2 = SE3(x2)

In [4]:
eta_matrix = X1.inv @ X2.to_matrix
eta = SE3.to_vec(eta_matrix)
eta

/Users/liyulin/git/LieGroup/lienp/SO3.py:242: RuntimeWarning: invalid value encountered in scalar divide
  q2[0] = (R[2, 1] - R[1, 2]) / (4 * b2)
/Users/liyulin/git/LieGroup/lienp/SO3.py:244: RuntimeWarning: invalid value encountered in scalar divide
  q2[2] = (R[0, 1] + R[1, 0]) / (4 * b2)
/Users/liyulin/git/LieGroup/lienp/SO3.py:245: RuntimeWarning: invalid value encountered in scalar divide
  q2[3] = (R[0, 2] + R[2, 0]) / (4 * b2)
/Users/liyulin/git/LieGroup/lienp/SO3.py:248: RuntimeWarning: invalid value encountered in scalar divide
  q3[0] = (R[0, 2] - R[2, 0]) / (4 * b3)
/Users/liyulin/git/LieGroup/lienp/SO3.py:249: RuntimeWarning: invalid value encountered in scalar divide
  q3[1] = (R[0, 1] + R[1, 0]) / (4 * b3)
/Users/liyulin/git/LieGroup/lienp/SO3.py:251: RuntimeWarning: invalid value encountered in scalar divide
  q3[3] = (R[1, 2] + R[2, 1]) / (4 * b3)
/Users/liyulin/git/LieGroup/lienp/SO3.py:254: RuntimeWarning: invalid value encountered in scalar divide
  q4[0] = (R[1, 0] 

array([1., 1., 2., 0., 0., 0.])

In [5]:
X = SE3(np.array([-2.290075, 7.4340122, 1.0000000e-03,   0.0000000e+00, 0.0000000e+00,  0.0000000e+00]))

In [6]:
SE3.to_vec(X.to_matrix)

array([-2.2900750e+00,  7.4340122e+00,  1.0000000e-03,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00])

In [7]:
x = np.array([1,1,1,0,0,0])
y = np.array([2,4,6,0.01,0.02,0.03])
theta = x[3:6]

In [8]:
a = se3(x)
a

array([1, 1, 1, 0, 0, 0])

In [9]:
a.param.shape

(6,)

In [10]:
#test so3
a = so3(theta)
aw = a.wedge
print('wedge:', aw)
av = so3.vee(aw)
print('vee:', av)

A = DCM.exp(a) # return group of DCM
print('exp:', A)
theta_group = Euler.from_dcm(A)
print('exp_ele:', theta_group)

wedge: [[ 0. -0.  0.]
 [ 0.  0. -0.]
 [-0.  0.  0.]]
vee: [0. 0. 0.]
exp: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
exp_ele: [0. 0. 0.]


/Users/liyulin/git/LieGroup/lienp/SO3.py:98: RuntimeWarning: invalid value encountered in scalar divide
  A = np.where(np.abs(theta) < EPS, 1 - theta**2/6 + theta**4/120, np.sin(theta)/theta)
/Users/liyulin/git/LieGroup/lienp/SO3.py:99: RuntimeWarning: invalid value encountered in scalar divide
  B = np.where(np.abs(theta)<EPS, 0.5 - theta ** 2 / 24 + theta ** 4 / 720, (1 - np.cos(theta)) / theta ** 2)


In [11]:
# test SO3
B = DCM.from_euler(theta_group) # group of DCM
print('SO3:', B)
print('inv', B.inv)
b = DCM.log(B) # input of log should be group, return so3 algebra (which will show element)
print('log:', b.wedge)
print('log_v:', b)


SO3: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
inv [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
log: [[ 0. -0.  0.]
 [ 0.  0. -0.]
 [-0.  0.  0.]]
log_v: [0. 0. 0.]


/Users/liyulin/git/LieGroup/lienp/SO3.py:90: RuntimeWarning: invalid value encountered in scalar divide
  A = np.where(np.abs(theta) < EPS, 1 - theta**2/6 + theta**4/120, np.sin(theta)/theta)


In [12]:
# check inv and matmul for group
Binv = DCM(B.inv)
I = Binv*B
I2 = Binv@B

In [13]:
I2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
X

array([-2.2900750e+00,  7.4340122e+00,  1.0000000e-03,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00])

In [15]:
# matmul can also be used in np.array
B.inv@B.to_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# test se3
c = se3(x)
cw = c.wedge
print('element:', c)
print('wedge:', cw)
print('vee:', se3.vee(cw))

C = SE3.exp(c)
print('exp:', C.to_matrix)
print('exp_ele:', C)

element: [1 1 1 0 0 0]
wedge: [[ 0. -0.  0.  1.]
 [ 0.  0. -0.  1.]
 [-0.  0.  0.  1.]
 [ 0.  0.  0.  0.]]
vee: [1. 1. 1. 0. 0. 0.]
exp: [[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]
exp_ele: [1. 1. 1. 0. 0. 0.]


/Users/liyulin/git/LieGroup/lienp/SE3.py:128: RuntimeWarning: invalid value encountered in scalar divide
  C1 = np.where(np.abs(theta)<EPS, 1 - theta ** 2 / 6 + theta ** 4 / 120, np.sin(theta)/theta)
/Users/liyulin/git/LieGroup/lienp/SE3.py:129: RuntimeWarning: invalid value encountered in scalar divide
  C2 = np.where(np.abs(theta)<EPS, 0.5 - theta ** 2 / 24 + theta ** 4 / 720, (1 - np.cos(theta)) / theta ** 2)
/Users/liyulin/git/LieGroup/lienp/SE3.py:130: RuntimeWarning: invalid value encountered in scalar divide
  C = np.where(np.abs(theta)<EPS, 1/6 - theta ** 2 /120 + theta ** 4 / 5040, (1 - C1) / theta ** 2)


In [17]:
c.ad_matrix

array([[ 0., -0.,  0.,  0., -1.,  1.],
       [ 0.,  0., -0.,  1.,  0., -1.],
       [-0.,  0.,  0., -1.,  1.,  0.],
       [ 0.,  0.,  0.,  0., -0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -0.],
       [ 0.,  0.,  0., -0.,  0.,  0.]])

Note that the elements of SE3 Lie group has to use [x,y,z,theta1,theta2,theta3] (pos, euler angles)

if you have your angle in other format, use SO3 class to do the transformation first

In [18]:
# test SE3
D = SE3(SE3.to_vec(C.to_matrix))
print('SE3:', D.to_matrix)
print('inv:', D.inv)
d = SE3.log(D) 
print('log:', d)

SE3: [[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]
inv: [[ 1.  0.  0. -1.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1. -1.]
 [ 0.  0.  0.  1.]]
nan
log: [nan nan nan  0.  0.  0.]


/Users/liyulin/git/LieGroup/lienp/SE3.py:104: RuntimeWarning: invalid value encountered in scalar divide
  C1 = np.where(np.abs(theta)<EPS, 1 - theta ** 2 / 6 + theta ** 4 / 120, np.sin(theta)/theta)
/Users/liyulin/git/LieGroup/lienp/SE3.py:105: RuntimeWarning: invalid value encountered in scalar divide
  C2 = np.where(np.abs(theta)<EPS, 0.5 - theta ** 2 / 24 + theta ** 4 / 720, (1 - np.cos(theta)) / theta ** 2)
/Users/liyulin/git/LieGroup/lienp/SE3.py:106: RuntimeWarning: divide by zero encountered in scalar divide
  print((1 / theta**2) * (1 - C1 / (2 * C2)))
/Users/liyulin/git/LieGroup/lienp/SE3.py:106: RuntimeWarning: invalid value encountered in scalar multiply
  print((1 / theta**2) * (1 - C1 / (2 * C2)))
/Users/liyulin/git/LieGroup/lienp/SE3.py:110: RuntimeWarning: divide by zero encountered in scalar divide
  + (1 / theta**2) * (1 - C1 / (2 * C2)) * wSkew @ wSkew
/Users/liyulin/git/LieGroup/lienp/SE3.py:110: RuntimeWarning: invalid value encountered in scalar multiply
  + (1 / 

In [19]:
Dinv = SE3(SE3.to_vec(D.inv))
Dinv@D

array([0., 0., 0., 0., 0., 0.])

In [20]:
# check inv
D.to_matrix@D.inv

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

$$ad(x)*y = - ad(y)*x$$

In [24]:
x1 = np.array([1,2,3,0.1,0.12,0.13])
y1 = np.array([3,4,5,0.3,0.2,0.34])
se3(x1).ad_matrix@y1 + se3(y1).ad_matrix@x1

array([0.00000000e+00, 5.55111512e-17, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00])

In [25]:
x2 = np.array([1,2,0.1])
y2 = np.array([3,4,0.34])
se2(x2).ad_matrix@y2 + se2(y2).ad_matrix@x2

array([0., 0., 0.])

$$Ad(\exp([x]^{\wedge})) = \exp(ad([x]^{\wedge})) $$

In [26]:
from scipy import linalg

/opt/anaconda3/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [27]:
SE3.exp(se3(x1)).Ad_matrix

array([[ 0.98440379, -0.12312763,  0.12565336, -0.62593589, -2.78916762,
         2.17065455],
       [ 0.13508639,  0.98659623, -0.09153989,  3.10661182, -0.48668399,
        -0.66090972],
       [-0.11269804,  0.10708628,  0.98784193, -1.74370975,  1.27688604,
        -0.33735119],
       [ 0.        ,  0.        ,  0.        ,  0.98440379, -0.12312763,
         0.12565336],
       [ 0.        ,  0.        ,  0.        ,  0.13508639,  0.98659623,
        -0.09153989],
       [ 0.        ,  0.        ,  0.        , -0.11269804,  0.10708628,
         0.98784193]])

In [28]:
SE3.exp(se3(x1)).Ad_matrix - linalg.expm(se3(x1).ad_matrix)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  4.44089210e-16],
       [ 2.77555756e-17,  1.11022302e-16,  0.00000000e+00,
         0.00000000e+00, -1.11022302e-16, -2.22044605e-16],
       [-1.38777878e-17,  0.00000000e+00,  2.22044605e-16,
         6.66133815e-16,  4.44089210e-16,  5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.77555756e-17,  1.11022302e-16,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.38777878e-17,  0.00000000e+00,  2.22044605e-16]])

In [29]:
SE2.exp(se2(x2)).Ad_matrix

array([[ 0.99500417, -0.09983342,  2.04662668],
       [ 0.09983342,  0.99500417, -0.89841747],
       [ 0.        ,  0.        ,  1.        ]])

In [30]:
SE2.exp(se2(x2)).Ad_matrix - linalg.expm(se2(x2).ad_matrix)

array([[-1.11022302e-16,  1.38777878e-17,  4.44089210e-16],
       [-1.38777878e-17, -1.11022302e-16,  1.22124533e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [3]:
D2 = SO2(np.array([1]))

In [4]:
D2inv = D2.inv
SO2(SO2.to_vec(D2inv))@D2

array([0.])

In [3]:
D3 = SE2(np.array([1,2,0.3]))

In [6]:
D3inv = D3.inv
SE2(SE2.to_vec(D3inv))@D3

array([-0.95462056,  0.91397124,  0.        ])